-- ============================================================================
-- V1: 初期スキーマ
--
-- このファイルは Java 側にのみ存在する。Kotlin 側は ddl-auto=validate で
-- このスキーマに追従するだけで、マイグレーションを持たない。
-- スキーマを変更するときは、必ずここに新しい V マイグレーションを追加し、
-- 両方のエンティティを更新すること。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- ユーザーと認証
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- メールアドレスは小文字に正規化してから保存する（アプリ側の責務）
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS 'アプリケーションのユーザー';

-- リフレッシュトークン。DB に保持して個別に失効できるようにする。
-- 生のトークンは保存せず、SHA-256 ハッシュのみを保存する。
CREATE TABLE refresh_tokens (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------------
-- プロフィールと目標
-- ---------------------------------------------------------------------------

-- 目標カロリーの自動算出（Mifflin-St Jeor 式）に必要な身体情報。
-- 体重は日々変わるため、ここではなく body_records の最新値を使う。
CREATE TABLE user_profiles (
    user_id        BIGINT       PRIMARY KEY,
    sex            VARCHAR(10)  NOT NULL,
    birth_date     DATE         NOT NULL,
    height_cm      NUMERIC(4,1) NOT NULL,
    activity_level VARCHAR(20)  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- Mifflin-St Jeor 式は男女で定数が異なるため、この 2 値のみを許可する
    CONSTRAINT ck_user_profiles_sex CHECK (sex IN ('MALE', 'FEMALE')),
    CONSTRAINT ck_user_profiles_activity CHECK (
        activity_level IN ('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE')
    ),
    CONSTRAINT ck_user_profiles_height CHECK (height_cm BETWEEN 50 AND 250)
);

-- 目標は履歴として複数行持ち、start_on で「その日に有効な目標」を引く。
-- 過去の達成率を後から計算し直せるようにするため、上書きしない。
CREATE TABLE goals (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    start_on          DATE         NOT NULL,
    target_kcal       INTEGER      NOT NULL,
    target_protein_g  NUMERIC(6,1) NOT NULL,
    target_fat_g      NUMERIC(6,1) NOT NULL,
    target_carb_g     NUMERIC(6,1) NOT NULL,
    pace_kg_per_month NUMERIC(4,2),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_goals_user_start UNIQUE (user_id, start_on),
    CONSTRAINT ck_goals_kcal CHECK (target_kcal BETWEEN 500 AND 10000)
);

-- ---------------------------------------------------------------------------
-- 体組成
-- ---------------------------------------------------------------------------

CREATE TABLE body_records (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    recorded_on  DATE         NOT NULL,
    weight_kg    NUMERIC(5,2) NOT NULL,
    body_fat_pct NUMERIC(4,1),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_body_records_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- 1 日 1 レコード。同じ日の再入力は UPDATE になる。
    CONSTRAINT uq_body_records_user_date UNIQUE (user_id, recorded_on),
    CONSTRAINT ck_body_records_weight CHECK (weight_kg BETWEEN 20 AND 300),
    CONSTRAINT ck_body_records_fat CHECK (body_fat_pct IS NULL OR body_fat_pct BETWEEN 1 AND 70)
);

-- ---------------------------------------------------------------------------
-- 食品マスタ
-- ---------------------------------------------------------------------------

-- 栄養値はすべて「可食部 100g あたり」で保持する。
-- 分量に応じた換算はアプリ側で行い、記録時に meal_log_items へ確定値を書く。
CREATE TABLE foods (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- MEXT: 日本食品標準成分表 / OFF: Open Food Facts / USER: ユーザーの手動登録
    source             VARCHAR(10)   NOT NULL,
    -- 出典側のコード（成分表の食品番号、OFF のバーコード等）。USER の場合は NULL。
    source_code        VARCHAR(64),
    name               VARCHAR(200)  NOT NULL,
    name_kana          VARCHAR(200),
    category           VARCHAR(100),
    kcal               NUMERIC(7,2)  NOT NULL,
    protein_g          NUMERIC(7,2)  NOT NULL DEFAULT 0,
    fat_g              NUMERIC(7,2)  NOT NULL DEFAULT 0,
    carb_g             NUMERIC(7,2)  NOT NULL DEFAULT 0,
    salt_g             NUMERIC(7,3),
    fiber_g            NUMERIC(7,2),
    sugar_g            NUMERIC(7,2),
    -- USER 登録の場合の作成者。マスタ由来の食品は NULL。
    created_by_user_id BIGINT,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_foods_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_foods_source CHECK (source IN ('MEXT', 'OFF', 'USER')),
    CONSTRAINT ck_foods_kcal CHECK (kcal >= 0),
    -- USER 登録には必ず作成者が要る。マスタ由来には作成者がいない。
    CONSTRAINT ck_foods_owner CHECK (
        (source = 'USER' AND created_by_user_id IS NOT NULL)
        OR (source <> 'USER' AND created_by_user_id IS NULL)
    )
);

-- 同じ出典の同じコードは 1 件だけ。source_code が NULL の USER 登録は対象外。
CREATE UNIQUE INDEX uq_foods_source_code ON foods (source, source_code) WHERE source_code IS NOT NULL;

-- 食品名の部分一致検索用。Phase 3 で件数が増えたら pg_trgm を検討する。
CREATE INDEX ix_foods_name ON foods (name);

-- 1 つの食品に複数の JAN コードが紐づくことがある（内容量違いの同一商品など）
CREATE TABLE food_barcodes (
    barcode    VARCHAR(20) PRIMARY KEY,
    food_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_food_barcodes_food FOREIGN KEY (food_id) REFERENCES foods (id) ON DELETE CASCADE
);

CREATE INDEX ix_food_barcodes_food ON food_barcodes (food_id);

-- ---------------------------------------------------------------------------
-- 食事記録
-- ---------------------------------------------------------------------------

CREATE TABLE meal_logs (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    eaten_on   DATE        NOT NULL,
    meal_type  VARCHAR(20) NOT NULL,
    note       VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_meal_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_meal_logs_type CHECK (meal_type IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK'))
);

-- 日別集計の主経路。(user_id, eaten_on) で範囲検索する。
CREATE INDEX ix_meal_logs_user_date ON meal_logs (user_id, eaten_on);

-- 【重要な設計判断】
-- 栄養値を foods への参照で持たず、登録時点の値をこの行に確定値として複写する。
-- 食品マスタは成分表の改訂やユーザーの修正で変わるが、
-- 「その日に何 kcal 食べたか」という記録は後から変わってはならない。
-- 正規化のセオリーから外れた意図的な非正規化であり、削ってはならない。
CREATE TABLE meal_log_items (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_log_id BIGINT       NOT NULL,
    -- 由来の食品。マスタから消えても記録は残るため NULL 許容。
    food_id     BIGINT,
    -- 以下は登録時点のスナップショット
    food_name   VARCHAR(200) NOT NULL,
    amount_g    NUMERIC(8,2) NOT NULL,
    kcal        NUMERIC(8,2) NOT NULL,
    protein_g   NUMERIC(8,2) NOT NULL DEFAULT 0,
    fat_g       NUMERIC(8,2) NOT NULL DEFAULT 0,
    carb_g      NUMERIC(8,2) NOT NULL DEFAULT 0,
    salt_g      NUMERIC(8,3),
    fiber_g     NUMERIC(8,2),
    sugar_g     NUMERIC(8,2),
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_meal_log_items_log FOREIGN KEY (meal_log_id) REFERENCES meal_logs (id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_log_items_food FOREIGN KEY (food_id) REFERENCES foods (id) ON DELETE SET NULL,
    CONSTRAINT ck_meal_log_items_amount CHECK (amount_g > 0),
    CONSTRAINT ck_meal_log_items_kcal CHECK (kcal >= 0)
);

CREATE INDEX ix_meal_log_items_log ON meal_log_items (meal_log_id);

-- ---------------------------------------------------------------------------
-- テンプレート（「いつもの朝食」）
-- ---------------------------------------------------------------------------

CREATE TABLE meal_templates (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    meal_type  VARCHAR(20),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_meal_templates_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_meal_templates_user_name UNIQUE (user_id, name),
    CONSTRAINT ck_meal_templates_type CHECK (
        meal_type IS NULL OR meal_type IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')
    )
);

-- テンプレートは「食品と分量の組」だけを持ち、栄養値は持たない。
-- 適用した瞬間に最新のマスタ値でスナップショットを作るため。
CREATE TABLE meal_template_items (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT       NOT NULL,
    food_id     BIGINT       NOT NULL,
    amount_g    NUMERIC(8,2) NOT NULL,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_meal_template_items_template FOREIGN KEY (template_id) REFERENCES meal_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_template_items_food FOREIGN KEY (food_id) REFERENCES foods (id) ON DELETE CASCADE,
    CONSTRAINT ck_meal_template_items_amount CHECK (amount_g > 0)
);

CREATE INDEX ix_meal_template_items_template ON meal_template_items (template_id);

-- ---------------------------------------------------------------------------
-- 運動（Phase 4 で使用。スキーマは先に用意しておく）
-- ---------------------------------------------------------------------------

CREATE TABLE activities (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    -- METs 値。消費kcal = METs × 体重kg × 時間h × 1.05
    mets       NUMERIC(4,2) NOT NULL,
    category   VARCHAR(50),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_activities_name UNIQUE (name),
    CONSTRAINT ck_activities_mets CHECK (mets > 0)
);

CREATE TABLE exercise_logs (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    performed_on  DATE         NOT NULL,
    activity_id   BIGINT,
    -- 食事記録と同じ理由で、算出時点の値をスナップショットとして保持する
    activity_name VARCHAR(100) NOT NULL,
    minutes       INTEGER      NOT NULL,
    kcal_burned   NUMERIC(8,2) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_exercise_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_exercise_logs_activity FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE SET NULL,
    CONSTRAINT ck_exercise_logs_minutes CHECK (minutes > 0),
    CONSTRAINT ck_exercise_logs_kcal CHECK (kcal_burned >= 0)
);

CREATE INDEX ix_exercise_logs_user_date ON exercise_logs (user_id, performed_on);
